image: gitpod/workspace-dotnet

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Postinstall dotnet LTS, dev certificates, and restore packages
    init: |
      mkdir -p /workspace/.dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel lts --install-dir /workspace/.dotnet
      dotnet dev-certs https 
      dotnet restore

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 32244
    onOpen: open-preview

# Add vscode extensions
vscode:
  extensions:
    - muhammad-sammy.csharp